### ISSUE TITLE
Mistake in .requestOne() method when type of "msg" (the second arg) is Number

### ISSUE THREAD

**Issue by noguilty4you** [nats-io/nats.js#296]
Hi guys, it looks like you have created 3 different interfaces for .requestOne() method, but the longest of them (node_modules/nats/index.d.ts:182) works incorrect.

### Issue
When we provide a non-empty String or any Object, it works fine, but if we provide any Number, it causes an unexpected behavior.

nats.js version: 1.3.0
node version: 12.4.0
npm version: 6.11.3
OS: macOS 10.12.6

### Code to reproduce

```
const NATS = require('nats/index')

const nats = NATS.connect('nats://localhost:4222', {
    pedantic: true,
    json: true,
    maxReconnectAttempts: 1000,
    reconnectTimeWait: 2000,
    waitOnFirstConnect: true
})



nats.on('connect', () => {

    nats.subscribe('foo', (msg, reply) => {
        nats.publish(reply, 'handled')
    })


    /**
     * The queue is not important here, but to reproduce the bug we need to use 
     * the longest signature of the .requestOne() method
     */
    
     /** the msg arg is a String, all will be ok */
     nats.requestOne('foo', 'some_string', {queue: 'worker'}, 10000, (result) => {
            console.log({result})
     })
    
    /** the msg arg an Object, all will be ok */
     nats.requestOne('foo', {}, {queue: 'worker'}, 10000, (result) => {
            console.log({result})
     })

    /** the msg arg is Number and the lib will throw an err */   
     nats.requestOne('foo', 123, {queue: 'worker'}, 10000, (result) => { 
            console.log({result})
     })
    
 })
```  

### Output
```
TypeError: conf.callback is not a function
    at Object.callback (/Users/***/Documents/projects/***/node_modules/nats/lib/nats.js:1932:26)
    at Client.processMsg (/Users/***/Documents/projects/***/node_modules/nats/lib/nats.js:1363:21)
    at Client.processInbound (/Users/***/Documents/projects/***/node_modules/nats/lib/nats.js:1237:22)
    at Socket.<anonymous> (/Users/***/Documents/projects/***/node_modules/nats/lib/nats.js:738:14)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by aricart** [comment]
@noguilty4you thanks for the report. I have a fix up for review. I will release as soon as that gets merged.

**Comment by noguilty4you** [comment]
@aricart , thanx you for quick reaction
