### ISSUE TITLE
nats.js should reconnect when one of nats servers are restarting

### ISSUE THREAD

**Issue by andriisoldatenko** [nats-io/nats.js#370]
Run nats cluster:

Server A:
```
nats-server -p 4222 -cluster nats://localhost:4248 -routes nats://localhost:4248 -m 8222
```

Server B:
```
nats-server -p 5222 -cluster nats://localhost:5248 -routes nats://localhost:4248
```

Run nats-streaming-server in cluster mode:
```
nats-streaming-server -ns nats://0.0.0.0:4222 --cluster_id nats-streaming --clustered --cluster_bootstrap --cluster_node_id nats-streaming-1 --cluster_raft_logging --debug --dir store-b --store file
```

Go to examples and start it using `yarn start`:
when it start and running try to kill `cluster A`

**Actual results:**
```
2020-08-25T00:47:14 ERROR NatsError: Could not connect to server: Error: connect ECONNREFUSED 127.0.0.1:4222
    at Socket.<anonymous> (/Users/andrii/workspace/src/github.com/astronomer/houston-api/node_modules/nats/lib/nats.js:801:26)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Expected results:

fallback to one of available nodes e.g. `cluster B`

P.S. golang client for nats works as expected:

```
go run main.go -s nats://127.0.0.1:4222 -t sub
Listening on [sub]
2020/08/25 02:17:22 Disconnected due to:EOF, will attempt reconnects for 10m
2020/08/25 02:17:22 Reconnected [nats://192.168.1.232:5222]
2020/08/25 02:17:37 Disconnected due to:EOF, will attempt reconnects for 10m
2020/08/25 02:17:37 Reconnected [nats://127.0.0.1:4222]
```

**Comment by aricart** [comment]
Did you specify the `waitOnFirstConnect` option?

**Comment by aricart** [comment]
Similar exercise to yours:
```bash
node notifications.js
connect to localhost:4222
connect to localhost:4222
disconnect
disconnect
reconnect to 192.168.86.52:5222
reconnect to 192.168.86.52:5222
disconnect
disconnect
reconnect to localhost:4222
reconnect to localhost:4222
disconnect
disconnect
reconnect to 192.168.86.52:5222
reconnect to 192.168.86.52:5222
disconnect
disconnect
reconnect to localhost:4222
reconnect to localhost:4222
```

**Comment by aricart** [comment]
If the initial startup sequence happens before a server is up, and the clients exhaust their reconnect policy they will close.  The only way to eliminate any timing issue is to specify the `waitOnFirstConnect` which effectively ignores max number of reconnection attempts until at least one connection is established. I believe the go client just recently added a similar flag.

**Comment by andriisoldatenko** [comment]
@aricart ty! yeah i can confirm it works using nats.js!

**Comment by aricart** [comment]
Excellent!
