### ISSUE TITLE
 Error between NATS and Promises

### ISSUE THREAD

**Issue by jefer94** [nats-io/nats.js#373]
Promise is resolved with success status

```typescript
export function subscribe<T>(service: string): Promise<Record<string, unknown>> {
  return new Promise((resolve, reject) => {
    resolve({ token: '!aasdasdasdsadsa' })  // in this scope if I call resolve, I get resolve this promise
    nc.subscribe(service, function (msg): void {
    } )
  })
}
```

Promise is never resolved with success status

```typescript
export function subscribe<T>(service: string): Promise<Record<string, unknown>> {
  return new Promise((resolve, reject) => {
    nc.subscribe(service, function (msg): void {
      resolve({ token: '!aasdasdasdsadsa' }) // in this scope if I call resolve, nothing happen
    } )
  })
}
```

Ticket #182 that not work to me

Example of my use case

```typescript
// ./nats.ts
type Msg = Record<string, unknown>
type FetchMsg = (_: unknown, message: Msg, ctx: Request) => Promise<Msg>

// GraphQL resolver
export function fetchMsgWithAuth(service: string, project: string): FetchMsg {
  return (_, message, ctx) => {
    if (ctx.auth?.user) {
      const channel = publish(service, project, message)
      return subscribe(channel)
    }
    throw ctx.error
  }
}

// that function is my issue
export function subscribe<T>(service: string): Promise<T> {
  return new Promise((resolve, reject) => {
    const id = nc.subscribe(service, (msg) => {
      if (msg.error) reject(msg.error)
      else resolve(msg.data)
      nc.unsubscribe(id)
    })
  })
}

export function publish<T>(service: string, action: string, message: Record<string, T>): string {
  const channel = keychain(service) // @chocolab/keychain, provide incremental string, this maybe unique just if that service contain only one instance
  nc.publish(service, { type: action, ...message }, channel)
  return channel
}
```

```typescript
// ./resolvers/query.ts
export enum projectsRefs {
  ...
  getProjectPermission = 'get project permission',
  ...
}

export enum serviceRefs {
  ...
  projects = 'projects',
}

const projects = {
  ...
  getProjectPermission: fetchMsgWithAuth(serviceRefs.projects, projectsRefs.getProjectPermission)
}

export default { ...authenticator, ...projects }
```

I just want publish one request, get response and close the subscription, thanks for you time

**Comment by aricart** [comment]
You may want to look into nats.ts or look at nats.js@beta, where requests
return a promise to the response.

**Comment by jefer94** [comment]
Ok, nats.ts will merge with nats.js in some future release? It would be great if in the future it is just a repo

**Comment by derekcollison** [comment]
Yes that is the plan.

**Comment by jefer94** [comment]
Nats.ts have that issue

```
(node:1) UnhandledPromiseRejectionWarning: TypeError: nc.on is not a function
    at /usr/src/services/current/node_modules/ts-nats/lib/nats.js:51:16
    at new Promise (<anonymous>)
    at Function.connect (/usr/src/services/current/node_modules/ts-nats/lib/nats.js:48:16)
    at Object.connect (/usr/src/services/current/node_modules/ts-nats/lib/nats.js:255:19)
    at Object.<anonymous> (/usr/src/services/current/dist/nats.js:56:21)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
```

**Comment by jefer94** [comment]
The promise issue is of node

**Comment by aricart** [comment]
> Ok, nats.ts will merge with nats.js in some future release? It would be great if in the future it is just a repo

v2 for NATS will obsolesce nats.ts as it provides the async API directly from nats.js.

**Comment by aricart** [comment]
> Nats.ts have that issue
> 
> ```
> (node:1) UnhandledPromiseRejectionWarning: TypeError: nc.on is not a function
>     at /usr/src/services/current/node_modules/ts-nats/lib/nats.js:51:16
>     at new Promise (<anonymous>)
>     at Function.connect (/usr/src/services/current/node_modules/ts-nats/lib/nats.js:48:16)
>     at Object.connect (/usr/src/services/current/node_modules/ts-nats/lib/nats.js:255:19)
>     at Object.<anonymous> (/usr/src/services/current/dist/nats.js:56:21)
>     at Module._compile (internal/modules/cjs/loader.js:1076:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:941:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:782:14)
>     at Module.require (internal/modules/cjs/loader.js:965:19)
> ```

Not seeing your code there, but `connect` on nats.ts returns a promise to the connection.
