### ISSUE TITLE
Nats connect using default CA certs/tls

### ISSUE THREAD

**Issue by s0n00im** [nats-io/nats.js#402]
Hi, 

Instead of providing the certs via:
```
let nc = await connect({
    url: url,
    tls: {
        ca: [caCert],
        key: [clientKey],
        cert: [clientCert]
    }
});
```

I want to setup tls options using my system CA certs. I know all the required certs are present in my docker base image.  
I setup le tls: {} and pass this empty tls to nats connect.
The documentation says When not present, default to the system trust store but I get the following error:

`Error: unable to verify the first certificate`
`Error: NC Error
    at Client.nc.on (/app/producer/client-node/dist/components/client.js:514:24)
    at Client.emit (events.js:193:13)
    at TLSSocket.stream.on (/app/producer/client-node/node_modules/nats/lib/nats.js:833:12)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)`

Can you tell me how to point nats to use the default system certs?

**Comment by aricart** [comment]
@s0n00im as I understand it, the default trust store is built into node itself, and it is fixed.
If you have a custom CA, you have to specify the files. You may also be able to use environment variables, but this will require flags on node to be honored. See https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file.
