### ISSUE TITLE
Window not defined Error when using jsm.streams.getMessage("streamname", 1) syntax

### ISSUE THREAD

**Issue by 300LiterPropofol** [nats-io/nats.js#428]
Hi! Thanks for your awesome work on NATS/Jetstream's javascript client. 

I encountered an error when I am using `getMessage` function.
The code line that has an error is just the same as in the [tutorial](https://github.com/nats-io/nats.deno/blob/main/jetstream.md).
```
let sm = await jsm.streams.getMessage(stream, 1);
```

The error is as below:
```
ReferenceError: window is not defined
at StoredMsgImpl._parse (/node_modules/nats/lib/nats-base-client/jsstream_api.js:121:20)
at new StoredMsgImpl (/node_modules/nats/lib/nats-base-client/jsstream_api.js:111:45)
at StreamAPIImpl.<anonymous> (/node_modules/nats/lib/nats-base-client/jsstream_api.js:98:20)
at Generator.next (<anonymous>)
at fulfilled (/node_modules/nats/lib/nats-base-client/jsstream_api.js:19:58)
at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
I felt the error quite confusing and does not understand what is happening behind it.
Has anyone encountered same error and have some ideas?
Thanks!

**Comment by aricart** [comment]
Thanks for catching this. The common library shared by both deno and browser have a global atob, which node doesn't.

**Comment by 300LiterPropofol** [comment]
Thanks for replying! Does that mean I can not use `<jsm.streams.getMessage()>` function if I am using nodejs if my interpretation of your reply is right?

**Comment by aricart** [comment]
Yes. If you skip that for now all else should be working. I'll release a fix first thing next week!

**Comment by 300LiterPropofol** [comment]
Thank you very much for the clarification! That's really helpful. I will close this issue.

**Comment by aricart** [comment]
I'll keep it open as a task...

**Comment by aricart** [comment]
@300LiterPropofol `npm install nats@latest` to get the fix.
