### ISSUE TITLE
BAD_HEADER error when receive message with headers from java client

### ISSUE THREAD

**Issue by StanislavGorobzeev** [nats-io/nats.js#430]
Hi! I faced with problem of this error while send message from java client to js client with headers.

Nats Server:
```
nats_1              | [1] 2021/06/01 14:24:20.505051 [INF] Starting nats-server
nats_1              | [1] 2021/06/01 14:24:20.505264 [INF]   Version:  2.2.6
nats_1              | [1] 2021/06/01 14:24:20.505285 [INF]   Git:      [cf433ae]
nats_1              | [1] 2021/06/01 14:24:20.505489 [DBG]   Go build: go1.16.4
```
Logs from nats server:

```
nats_1              | [1] 2021/06/01 14:04:51.340544 [TRC] 192.168.0.1:40860 - cid:3 - "v2.11.3:java:nats://localhost:4222" - <<- [HPUB realtime_control 23 237]
nats_1              | [1] 2021/06/01 14:04:51.340809 [TRC] 192.168.0.1:40860 - cid:3 - "v2.11.3:java:nats://localhost:4222" - <<- MSG_PAYLOAD: ["NATS/1.0\r\nkey:value\r\n\r\n{\"controlStreamName\":\"audio_xAYYyszRUP\",\"accountId\":\"********-****-****-****-************\",\"timestamp\":\"2021-06-01T14:04:51Z\",\"asrConfig\":{\"language\":\"english\"},\"checklistId\":\"********-****-****-****-************\"}"]
nats_1              | [1] 2021/06/01 14:04:51.341485 [TRC] 192.168.0.11:38402 - cid:4 - "v2.0.4:nats.js" - ->> [HMSG realtime_control 1 23 237]
nats_1              | [1] 2021/06/01 14:04:51.341748 [TRC] 192.168.0.12:43554 - cid:5 - "v2.0.4:nats.js" - ->> [HMSG realtime_control 1 23 237]
```
Logs from js server
```
node-server_1      | > HMSG realtime_control 1 23 237␍␊NATS/1.0␍␊key:value␍␊␍␊{"controlStreamName":"audio_xAYYyszRUP","accountId":"********-****-****-****-************","timestamp":"2021-06-01T14:04:51Z","asrConfig":{"language":"english"},"checklistId":"********-****-****-****-************"}␍␊
node-server_1      | {"message":"Unhandled Rejection at: Promise {\n  <rejected> Error: Error receiving message from realtime_control: {\"name\":\"NatsError\",\"code\":\"BAD_HEADER\"}\n      at /opt/node-server/lib-streamer/lib/NatsClient.js:85:17\n      at processTicksAndRejections (internal/process/task_queues.js:93:5)\n} reason: Error: Error receiving message from realtime_control: {\"name\":\"NatsError\",\"code\":\"BAD_HEADER\"}\n    at /opt/node-server/lib-streamer/lib/NatsClient.js:85:17\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","level":"error"}
```

Example of java code sending:
```
    Message msg = NatsMessage.builder()
            .subject(topic)
            .headers(new Headers().add("key", "value"))
            .data(message.getPayload())
            .build();
    connection.publish(msg);
````

Example of js code consuming
```
async subscribe({
    topic,
    queue,
    callback
  }) {
    try {
      const subscription = this.nc.subscribe(topic, {
        queue
      });
      this.subscriptions.set(topic, subscription);

      (async () => {
        try {
          for await (const message of subscription) {
            const headers = {};

            if (message.headers) {
              for (const [key, value] of message.headers) { 
                if (Array.isArray(value) && value.length === 1) {
                  headers[key] = value[0];
                } else {
                  headers[key] = value;
                }
              }
            }

            callback(null, {
              topic,
              headers,
              body: Buffer.from(message.data)
            });
          }
        } catch (err) {
          throw Error(`Error receiving message from ${topic}:` + ` ${JSON.stringify(err)}`);
        }
      })();
    } catch (err) {
      throw Error(`Error subscribing to ${topic}: ${JSON.stringify(err)}`);
    }
  }
```

**Comment by aricart** [comment]
@StanislavGorobzeev what versions of the library (nats.js and nats.java) are you using?

**Comment by StanislavGorobzeev** [comment]
I am using 
v2.11.3 java 
v2.0.4 js

**Comment by aricart** [comment]
@scottf @kozlovic @ColinSullivan1 The issue is that the Java client took the unexpected serialization of separating header/values with just a `:`, rather than the recommended and mime required of `: `. Somehow the modifications to the ADR sneaked a change where we didn't require it even though some of the clients expect `: ` to be the separator, as not including the spacer introduces ambiguities on deserializing (should the value have space or not), and if so for how many spaces.

**Comment by kozlovic** [comment]
@aricart FYI, the Go and C clients will skip spaces after the `:`, so this is not an issue for those client libraries.

**Comment by aricart** [comment]
@kozlovic so trimming left OK?

**Comment by kozlovic** [comment]
I even trim right in the C client...

**Comment by aricart** [comment]
OK that change would be simpler.

**Comment by aricart** [comment]
@StanislavGorobzeev `npm install nats@latest` to get the fix
