### ISSUE TITLE
ECONNABORTED while connecting to nats-server

### ISSUE THREAD

**Issue by jatinseth2007** [nats-io/nats.js#459]
Hello Team,

I am using the nats-server to start my server and then trying to connect from nodejs but getting `ECONNABORTED ` error.

Nat server:

```
nats-server                    [18220] 2021/10/08 12:52:40.251379 [[32mINF[0m] Starting nats-server version 2.0.0
[18220] 2021/10/08 12:52:40.252378 [[32mINF[0m] Git commit [not set]
[18220] 2021/10/08 12:52:40.254378 [[32mINF[0m] Listening for client connections on 0.0.0.0:4222
[18220] 2021/10/08 12:52:40.254378 [[32mINF[0m] Server id is NDCMFSXRIDH35VCP4HPV2OV6MOCX3YOT2MH7NTMN6P2QY5E44HMHNMUM
[18220] 2021/10/08 12:52:40.254378 [[32mINF[0m] Server is ready
```

nodejs script:
```
const { connect: NAT_CONNECT } = require("nats");

const testNatServer = async () => {
    try {
        const nc = await NAT_CONNECT({
            pingInterval: 20 * 1000, //20s
            maxPingOut: 5,
            url: "nats://localhost:4222"
        });
        console.log("connected to ${nc}");
    } catch (error) {
        console.log(error);
    }
};

testNatServer();
```

Error:

```
(node:20072) UnhandledPromiseRejectionWarning: Error: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:798:11)
    at Socket._write (net.js:810:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at NodeTransport.send (C:\Users\jseth\projects\internal\nodenatsexample\node_modules\nats\lib\src\node_transport.js:326:21)
```

**Comment by wallyqs** [comment]
How about adding something like this to debug the closing error? https://github.com/nats-io/nats.js/blob/master/examples/nats-sub.js#L52-L57
