### ISSUE TITLE
streams.update(config: StreamConfig) api changed ... update your code.

### ISSUE THREAD

**Issue by raarts** [nats-io/nats.js#488]
I get this warning in my nestjs startup:

```
Trace:  >> streams.update(config: StreamConfig) api changed to streams.update(name: string, config: StreamUpdateConfig) - this shim will be removed - update your code.
    at StreamAPIImpl.<anonymous> (/Users/raarts/work/company/group/product/node_modules/nats/nats-base-client/jsmstream_api.ts:73:15)
    at Generator.next (<anonymous>)
    at /Users/raarts/work/company/group/product/node_modules/nats/lib/nats-base-client/jsmstream_api.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/raarts/work/company/group/product/node_modules/nats/lib/nats-base-client/jsmstream_api.js:18:12)
    at StreamAPIImpl.update (/Users/raarts/work/company/group/product/node_modules/nats/lib/nats-base-client/jsmstream_api.js:54:16)
    at NatsJetStreamServer.setupStream (/Users/raarts/work/company/group/product/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/server.ts:121:49)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at NatsJetStreamServer.listen (/Users/raarts/work/company/group/product/node_modules/@nestjs-plugins/nestjs-nats-jetstream-transport/src/server.ts:36:7)
```

NATS Server info string:
```
INFO {"server_id":"NAUHO4CHDVCL5V5BB24HFVDBZG73GGAZS7GW3MQGRWH7LJIVLW6JHNIF","server_name":"NAUHO4CHDVCL5V5BB24HFVDBZG73GGAZS7GW3MQGRWH7LJIVLW6JHNIF","version":"2.7.3","proto":1,"git_commit":"1712ee3","go":"go1.17.7","host":"0.0.0.0","port":4222,"headers":true,"max_payload":1048576,"jetstream":true,"client_id":17,"client_ip":"172.20.0.1"}
```

natsjs version 2.6.1

Using nats with npm package `@nestjs-plugins/nestjs-nats-jetstream-transport`

EDIT: The very first time my service starts (against a completely fresh nats service with `-js` enabled) I do *NOT* get this error. After that I get it on all invocations. This now leads me to believe I should report this error to the maintainer of `@nestjs-plugins/nestjs-nats-jetstream-transport`. 

Do you agree?

**Comment by aricart** [comment]
Looks like it was fixed already.

**Comment by amir2227** [comment]
how can i fix this error
