### ISSUE TITLE
Closed connection with 'Stale Connection' error doesn't auto-reconnect

### ISSUE THREAD

**Issue by ArmorDarks** [nats-io/nats.js#531]
* Client version: 2.8.0
* Node version: 16.14.2

## What's happening

Given the config

```ts
const connection = await connect({
  maxReconnectAttempts: -1,
  name: 'some-name',
  pass: 'some-pass',
  servers: ['load-balancer-url'],
  user: 'some-user',
  inboxPrefix: 'some.inbox',
})
```

If the connection closed with the following error

```
NatsError: 'Stale Connection'
    at Function.toError (/code/node_modules/nats/lib/nats-base-client/protocol.js:339:20)
    at ProtocolHandler.<anonymous> (/code/node_modules/nats/lib/nats-base-client/protocol.js:363:41)
    at Generator.next (<anonymous>)
    at /code/node_modules/nats/lib/nats-base-client/protocol.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/code/node_modules/nats/lib/nats-base-client/protocol.js:4:12)
    at ProtocolHandler.processError (/code/node_modules/nats/lib/nats-base-client/protocol.js:361:16)
    at ProtocolHandler.push (/code/node_modules/nats/lib/nats-base-client/protocol.js:461:22)
    at Parser.parse (/code/node_modules/nats/lib/nats-base-client/parser.js:307:45)
    at ProtocolHandler.<anonymous> (/code/node_modules/nats/lib/nats-base-client/protocol.js:197:45)
```

it will never reconnect despite `maxReconnectAttempts` set to `-1`

## What's expected

If `maxReconnectAttempts` set to `-1`, the connection should automatically try reconnecting. Otherwise, it should be highlighted in the docs that this particular case has to be handled manually.

**Comment by ArmorDarks** [comment]
Caught a similar error while restarting one of the NATS nodes (behind the balancer) on a few clients (servers too). Maybe just a coincidence, though. Here's what it logged:

<img width="2131" alt="image" src="https://user-images.githubusercontent.com/4460311/201963673-d250dee0-5fba-4dde-b3fb-0ac87f62a7d8.png">

**Comment by aricart** [comment]
This is again some condition where the load balancer is doesn't have a connection and the  ping requests from the client are going unanswered.

```javascript
import { createServer } from "net";
import { connect } from "nats";

const PORT = 4532;

let INFO = Buffer.from(
  `INFO {"server_id":"FAKE","server_name":"FAKE","version":"2.9.4","proto":1,"go":"go1.19.2","host":"127.0.0.1","port":${PORT},"headers":true,"max_payload":1048576,"jetstream":true,"client_id":4,"client_ip":"127.0.0.1"}\r\n`,
);

const PING = { re: /^PING\r\n/i, out: "PONG\r\n" };
const CONNECT = { re: /^CONNECT\s+([^\r\n]+)\r\n/i, out: "" };
const CMDS = [PING, CONNECT];

const server = createServer();
server.on("connection", (conn) => {
  console.log("client connected");
  conn.write(INFO);

  let inbound;
  conn.sentPong = false;
  conn.on("data", (data) => {
    if (inbound) {
      inbound = Buffer.concat([inbound, data]);
    } else {
      inbound = data;
    }
    if (conn.sentPong) {
      inbound = Buffer.from("");
    }
    while (data.length > 0) {
      let m = null;
      for (let i = 0; i < CMDS.length; i++) {
        m = CMDS[i].re.exec(inbound);
        if (m) {
          const len = m[0].length;
          if (len <= inbound.length) {
            inbound = inbound.slice(len);
            conn.write(Buffer.from(CMDS[i].out));
            if (CMDS[i].out === PING.out) {
              conn.sentPong = true;
            }
            break;
          }
        }
      }
      if (m === null) {
        break;
      }
    }
  });
});

server.listen(PORT, (v) => {
});

const nc = await connect({
  port: PORT,
  debug: true,
  maxReconnectAttempts: -1,
  pingInterval: 2000,
  reconnectTimeWait: 500,
});

(async () => {
  for await (const s of nc.status()) {
    console.log(s);
  }
})();

nc.closed().then((err) => {
  console.log(`client closed with: ${err?.message}`);
  server.close();
});

```

If you run the above:

```bash
client connected
> INFO {"server_id":"FAKE","server_name":"FAKE","version":"2.9.4","proto":1,"go":"go1.19.2","host":"127.0.0.1","port":4532,"headers":true,"max_payload":1048576,"jetstream":true,"client_id":4,"client_ip":"127.0.0.1"}␍␊
< CONNECT {"protocol":1,"version":"2.9.0","lang":"nats.js","verbose":false,"pedantic":false,"headers":true,"no_responders":true}␍␊
< PING␍␊
> PONG␍␊
{ type: 'pingTimer', data: '1' }
< PING␍␊
{ type: 'pingTimer', data: '2' }
< PING␍␊
< 
{ type: 'pingTimer', data: '3' }
{ type: 'staleConnection', data: '' }
{ type: 'disconnect', data: '127.0.0.1:4532' }
{ type: 'reconnecting', data: '127.0.0.1:4532' }
client connected
> INFO {"server_id":"FAKE","server_name":"FAKE","version":"2.9.4","proto":1,"go":"go1.19.2","host":"127.0.0.1","port":4532,"headers":true,"max_payload":1048576,"jetstream":true,"client_id":4,"client_ip":"127.0.0.1"}␍␊
< CONNECT {"protocol":1,"version":"2.9.0","lang":"nats.js","verbose":false,"pedantic":false,"headers":true,"no_responders":true}␍␊
< PING␍␊
{ type: 'update', data: { added: [], deleted: [] } }
> PONG␍␊
{ type: 'reconnect', data: '127.0.0.1:4532' }
{ type: 'pingTimer', data: '1' }
< PING␍␊
{ type: 'pingTimer', data: '2' }
< PING␍␊
< 
{ type: 'pingTimer', data: '3' }
{ type: 'staleConnection', data: '' }
{ type: 'disconnect', data: '127.0.0.1:4532' }
{ type: 'reconnecting', data: '127.0.0.1:4532' }
client connected
> INFO {"server_id":"FAKE","server_name":"FAKE","version":"2.9.4","proto":1,"go":"go1.19.2","host":"127.0.0.1","port":4532,"headers":true,"max_payload":1048576,"jetstream":true,"client_id":4,"client_ip":"127.0.0.1"}␍␊
< CONNECT {"protocol":1,"version":"2.9.0","lang":"nats.js","verbose":false,"pedantic":false,"headers":true,"no_responders":true}␍␊
< PING␍␊
{ type: 'update', data: { added: [], deleted: [] } }
> PONG␍␊
{ type: 'reconnect', data: '127.0.0.1:4532' }
{ type: 'pingTimer', data: '1' }
< PING␍␊
{ type: 'pingTimer', data: '2' }
< PING␍␊
< 
{ type: 'pingTimer', data: '3' }
{ type: 'staleConnection', data: '' }
{ type: 'disconnect', data: '127.0.0.1:4532' }
{ type: 'reconnecting', data: '127.0.0.1:4532' }
...
^C⏎                                        
```
As you can see above the reports a stale connection, and then initiates another connection. This again is possibly a

**Comment by aricart** [comment]
@ArmorDarks I am going to close this issue, since as you can see on the released version, the connections do restart.

**Comment by ArmorDarks** [comment]
You can see with logging in 2.8.1-2 it reports too that connection was closed with that error:

![image](https://user-images.githubusercontent.com/4460311/202213086-c0f0da79-7700-4f67-824e-02d0409d9a6c.png)

It doesn't report any statuses like `disconnect`

**Comment by ArmorDarks** [comment]
Here's the most recent case

<img width="2121" alt="Screenshot 2022-11-16 at 15 03 24" src="https://user-images.githubusercontent.com/4460311/202216515-5f13fe4e-f1e2-40ae-8c60-79c184aca978.png">

As you can see, 2.8.1-2 doesn't report any status changes. It just closes the connection. Prior to this repot `connection.request` will report about timeouts (and other services will do the same).

**Comment by aricart** [comment]
All the tests I ran were with 2.9.0, let me try with 2.8.0

**Comment by ArmorDarks** [comment]
@aricart If I'm not mistaken, there's no difference between v2.8.1-2 and v2.9.0 except for the additional log in 2.8.1-2. Both seem to have the same fix and the same Deno base client v1.9.0, right? So that fix is already included in affected services.

**Comment by aricart** [comment]
I think there may have been smaller tweaks, I didn't annotate or formally tagged, so I am not sure what is or not there, I would recommend to move to 2.9.0, if you want me to add additional logging on 2.9.0 I can do that for you. Also for both our sanities:

https://github.com/aricart/nats-close-tests

Clone this repo and try to run the tests as shown - stored I want to make sure you replicate what I am seeing.
I was testing on node 18, not sure what version of the runtime you are doing.

**Comment by ArmorDarks** [comment]
>  I think there may have been smaller tweaks, I didn't annotate or formally tagged, so I am not sure what is or not there, I would recommend to move to 2.9.0, if you want me to add additional logging on 2.9.0 I can do that for you.

If that would be helpful to you for investigations - sure, let's add them

> Clone this repo and try to run the tests as shown - stored I want to make sure you replicate what I am seeing.
I was testing on node 18, not sure what version of the runtime you are doing.

I'm quite sure the tests will pass fine. It's either that 2.8.1-2 missing tweaks from 2.9.0, or it's some condition that we're missing.

**Comment by ArmorDarks** [comment]
@aricart Just caught that error on a server with client 2.9.1-0.

What's odd, there are no status changes or anything in the logs. Only a single error logged on `connection.closed()`:


```
NatsError: 'Stale Connection'
    at Function.toError (/code/node_modules/nats/lib/nats-base-client/protocol.js:339:20)
    at ProtocolHandler.<anonymous> (/code/node_modules/nats/lib/nats-base-client/protocol.js:363:41)
    at Generator.next (<anonymous>)
    at /code/node_modules/nats/lib/nats-base-client/protocol.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/code/node_modules/nats/lib/nats-base-client/protocol.js:4:12)
    at ProtocolHandler.processError (/code/node_modules/nats/lib/nats-base-client/protocol.js:361:16)
    at ProtocolHandler.push (/code/node_modules/nats/lib/nats-base-client/protocol.js:464:22)
    at Parser.parse (/code/node_modules/nats/lib/nats-base-client/parser.js:307:45)
    at ProtocolHandler.<anonymous> (/code/node_modules/nats/lib/nats-base-client/protocol.js:197:45)
```

After that connection never restarts.

Probably some odd race condition, which is not covered by tests?

**Comment by aricart** [comment]
stale connection is we didn't get server pings, but the socket was opened - sounds like an LB issue.
Now the question is why did the process stop - can you verify the connect options? We know from ☝️ that the client reconnects.

**Comment by aricart** [comment]
@ArmorDarks also released [2.9.1](https://github.com/nats-io/nats.js/releases/tag/v2.9.1)

**Comment by aricart** [comment]
I will take a look again tomorrow at it perhaps there's some mix of things that is still getting it to toss.

**Comment by aricart** [comment]
Can you please copy your current options for connect - I want to make sure that I am specifying exactly what you have.

**Comment by ArmorDarks** [comment]
@aricart Thank you

```ts
await connect({
  maxReconnectAttempts: -1,
  waitOnFirstConnect: true,
  reconnectJitter: 10_000,
  reconnectJitterTLS: 10_000,
  ignoreAuthErrorAbort: true,
  name: 'name',
  pass: 'pass',
  servers: ['3-pods-behind-balancer'], // single url - AWS Load Balancer + nats-operator
  user: 'user',
  inboxPrefix: 'service.inbox',
})
```

another interesting part is that there were no changes in statuses at all. Even `DebugEvent.StaleConnection` didn't fire. For clarity, we log all status changes except `DebugEvent.Ping`.

**Comment by aricart** [comment]
@ArmorDarks perfect - looking at it.

**Comment by aricart** [comment]
> @aricart Thank you
> 
> ```ts
> await connect({
>   maxReconnectAttempts: -1,
>   waitOnFirstConnect: true,
>   reconnectJitter: 10_000,
>   reconnectJitterTLS: 10_000,
>   ignoreAuthErrorAbort: true,
>   name: 'name',
>   pass: 'pass',

You meant `user` where you put `name` right - name is the client name.

**Comment by ArmorDarks** [comment]
@aricart `user` is a few lines below, under `servers`. In `name` we specify the client name`. Sorry for the confusing ordering.
