### ISSUE TITLE
NatsError: TIMEOUT

### ISSUE THREAD

**Issue by njavilas2015** [nats-io/nats.js#538]
Good evening, I am doing tests to migrate to nats.io, I started using the js language in nodejs.

I have created a small abstraction where it allows me to generate messages from a http gateway
I have managed to get the worker working as a group. which if I have multiple workers works great without any problems to resolve the requests.

But I notice that if there are many clients making requests, a NatsError: TIMEOUT error occurs.

Way to reproduce the error:
Firstly, I understand how little time they have and for this I have generated a repo to directly execute it, but I will also record it here for the record.

As I mentioned the abstraction would be the following:

```ts
import { Codec, connect, ConnectionOptions, Msg, NatsConnection, StringCodec, Subscription } from "nats";
import { setTimeout } from "timers/promises";

export class Worker {
  private opts: ConnectionOptions;
  private nc: NatsConnection;
  private sc: Codec<string>;
  private subject: string;

  constructor(subject: string, opts: ConnectionOptions) {

    this.sc = StringCodec();

    this.opts = opts;

    this.subject = subject;

    this.init();
  }

  async init() {

    this.nc = await connect(this.opts);

    this.nc.closed().then((err) => {
      err && console.error(`service exited because of error: ${err.message}`);
    });

    console.info(`connected ${this.nc.getServer()}`);
  }

  async close() {
    await this.nc.flush();

    await this.nc.close();
  }

  async run(queue: string, callBack: (payload: string) => Promise<string>) {

    await setTimeout(200);

    const sub: Subscription = this.nc.subscribe(this.subject, { queue });

    for await (const m of sub) {

      const payload: string = await callBack(this.sc.decode(m.data));

      m.respond(this.sc.encode(payload));
    }
  }
}

export class Api {

  private opts: ConnectionOptions;
  private nc: NatsConnection;
  private sc: Codec<string>;
  private subject: string;

  constructor(subject: string, opts: ConnectionOptions) {

    this.sc = StringCodec();

    this.opts = opts;

    this.subject = subject;

    this.init().then(() => console.info(`connected ${this.nc.getServer()}`));
  }

  async init() {
    this.nc = await connect(this.opts);

    this.nc.closed().then((err) => {
      err && console.error(`service exited because of error: ${err.message}`);
    });
  }

  async close() {
    await this.nc.flush();

    await this.nc.close();
  }

  async add<T, R>(payload: T): Promise<R> {

    const data: Uint8Array = this.sc.encode(JSON.stringify(payload));

    const start = Date.now();

    const message: Msg = await this.nc.request(this.subject, data, { timeout: 1000 });

    const end = Date.now();

    console.log(end - start, "ms");

    return JSON.parse(this.sc.decode(message.data));
  }
}

```

## Use of the same

```ts worker.ts
import { Worker } from "../pathofclass";
import { setTimeout } from "timers/promises";

const processing = async (payload: string): Promise<string> => {

  /*
    simulate delay of database
  */
  await setTimeout(100);

  return JSON.stringify(payload);
};

const worker: Worker = new Worker("hzsoejlmsmwilqt", {
  servers: "localhost:4222"
});

worker.run("group-a", processing);
```

Explanation of the principle of operation of the api
The idea is to define the constructor once and then execute the processing function to then send it to an http gateway, or another microservice can make requests.

```ts api.ts
import { Api } from "../pathofclass";

export interface User {
  fullName: string
  age: number
}

const api: Api = new Api("hzsoejlmsmwilqt", { servers: "localhost:4222" });

export const processing = async (payload: User): Promise<User> => {

  const result = await api.add<User, User>(payload);

  return result;
};

export default { processing };
```

## Tests performed

I simulate requests every 300ms

```js
const { processing } = require('./dist')

var counter = 0

setInterval(async () => {

  const result = await processing({ fullName: "Javier Avila", age: counter++ })

  console.log(counter, result)

}, 300);

```
tow client cpu 0% - 1%

# Error
```bash
workdir = /mnt/565b0cad-2497-47f1-81d0-719b7c33b11d/nats-io/queue

workdir/node_modules/.pnpm/nats@2.8.0/node_modules/nats/lib/nats-base-client/error.js:100
  return new NatsError(m, code, chainedError);
               ^

NatsError: TIMEOUT
    at NatsError.errorForCode (workdir/node_modules/.pnpm/nats@2.8.0/node_modules/nats/lib/nats-base-client/error.js:100:16)
    at timeout (workdir/node_modules/.pnpm/nats@2.8.0/node_modules/nats/lib/nats-base-client/util.js:88:35)
    at new SubscriptionImpl (workdir/node_modules/.pnpm/nats@2.8.0/node_modules/nats/lib/nats-base-client/subscription.js:31:45)
    at NatsConnectionImpl.subscribe (workdir/node_modules/.pnpm/nats@2.8.0/node_modules/nats/lib/nats-base-client/nats.js:118:21)
    at Worker.run (workdir/dist/index.js:27:29) {                                 
  code: 'TIMEOUT',
  chainedError: undefined
}

Node.js v18.12.1

```

**Comment by njavilas2015** [comment]
3 client cpu 0% - 1%
![image](https://user-images.githubusercontent.com/47610140/206884863-6166fa32-bffb-4eee-973d-4e26b34c18e4.png)

when adding more clients, if I don't immediately add another worker the client drops and this error occurs

which is a problem since it is impossible to determine the number of clients that a microservice can have

something surely I am wrong and it doesn't let me apply nats.io correctly, is there any way to prevent the client from crashing

**Comment by aricart** [comment]
The timeout is coming from:
 ` const message: Msg = await this.nc.request(this.subject, data, { timeout: 1000 });`
 note you are not handling the rejection.

The main issue is likely here - note how you are blocking the processing of other requests until you calculate the answer.

```
    const sub: Subscription = this.nc.subscribe(this.subject, { queue });
    for await (const m of sub) {

      const payload: string = await callBack(this.sc.decode(m.data));
                                             ^^^^^
      m.respond(this.sc.encode(payload));
    }
```

**Comment by aricart** [comment]
Just doing some simple math - for each request your service is taking 300ms, and you are only waiting 1000ms for a response, all it takes is 4 requests at the same time, for the fourth to timeout.

**Comment by njavilas2015** [comment]
happy new year!, I have made the change of the codec but I still do not understand very well from what I understand and from my experience in bullmq which is a message distributor like nats.io but on redis, I can start a worker and raise as many clients and each one will wait for your request to finish. It really supports almost a million requests in my case thousands without problems. The issue is that I cannot understand this since with 3 clients it is saturated and it still continues with a timeout. How can I process requests without this timeout?

**Comment by aricart** [comment]
@njavilas2015 - I think you missed the point. Let's try again.

```javascript    
const sub: Subscription = this.nc.subscribe(this.subject, { queue });
    for await (const m of sub) {

      const payload: string = await callBack(this.sc.decode(m.data));
                                             ^^^^^
      m.respond(this.sc.encode(payload));
    }
```


Clients are sending requests, they are buffering up. The requests for the client are being queued for the iterator to process, but you are not processing anything until the current request you are handling completes.

Try instead:
```javascript
for await(const m of sub) {
         callBack(this.sc.decode(m.data))
           .then((payload) => { m.respond(payload); })
           .catch((err) => { console.error(err); });
}
```

This will start invoking your callback for all other requests. When the callback function returns you a value, you'll send the response, but the difference is that all the other requests in parallel are calling your `callback` as well. So they start processing as soon as fast as the loop yields them to you.

**Comment by njavilas2015** [comment]
Thank you very much for your patience and willingness to respond so quickly. Thank you very much, I will pay attention to these small details. I'm a fullstack developer and whatever I can help I'm ready

**Comment by njavilas2015** [comment]
my final code working, in case someone is useful, @aricart  Thank you very much
```//worker.ts
import {
  Codec, connect, ConnectionOptions,
  NatsConnection, StringCodec, Subscription
} from "nats";

import { setTimeout } from "timers/promises";

class Worker {
  private opts: ConnectionOptions;
  private nc: NatsConnection;
  private sc: Codec<string>;
  private subject: string;

  constructor(name: string, opts: ConnectionOptions) {

    this.sc = StringCodec();

    this.opts = opts;

    this.subject = name;

    this.init();
  }

  async init() {

    this.nc = await connect(this.opts);

    this.nc.closed().then((err) => {
      err && console.error(`service exited because of error: ${err.message}`);
    });

    console.info(`connected ${this.nc.getServer()}`);
  }

  async close() {
    await this.nc.flush();

    await this.nc.close();
  }

  async run(callBack: (payload: string) => Promise<string>) {

    await setTimeout(200);

    const sub: Subscription = this.nc.subscribe(this.subject, { queue: "worker" });

    for await (const m of sub) {

      callBack(this.sc.decode(m.data))

        .then((payload: string) => m.respond(this.sc.encode(payload)))

        .catch((err) => console.error(err));
    }
  }
}
```
```//api.ts
import { Codec, connect, ConnectionOptions, Msg, NatsConnection, StringCodec } from "nats";

class Api {

  private opts: ConnectionOptions;
  private nc: NatsConnection;
  private sc: Codec<string>;
  private subject: string;

  constructor(subject: string, opts: ConnectionOptions) {

    this.sc = StringCodec();

    this.opts = opts;

    this.subject = subject;

    this.init().then(() => console.info(`connected ${this.nc.getServer()}`));
  }

  async init() {

    this.nc = await connect(this.opts);

    this.nc.closed().then((err) => {
      err && console.error(`service exited because of error: ${err.message}`);
    });
  }

  async close() {
    await this.nc.flush();

    await this.nc.close();
  }

  async add<T, R>(payload: T): Promise<R> {

    const data: Uint8Array = this.sc.encode(JSON.stringify(payload));

    const message: Msg = await this.nc.request(this.subject, data);

    return JSON.parse(this.sc.decode(message.data));
  }
}
```

```api.js
const { default: Api } = require('./dist/api')

const api = new Api("demo", { servers: "localhost:4222" })

var counter = 0

const main = async () => {

  setInterval(async () => {

    try {

      const result = await api.add({
        name: "Javier Avila",
        age: counter++
      })

      console.log(result)

    } catch (error) {
      console.log(error.message)
    }

  }, 100);
}

main()

```

```//worker.js
const { default: Worker } = require('./dist/worker')

var counter = 0

const main = async () => {

  const woker = new Worker("demo", { servers: "localhost:4222" })

  woker.run(async (payload) => {

   console.log({ payload })

    const result = await new Promise((resolve, reject) => {

      setTimeout(() => {
        resolve(JSON.stringify({ statusCode: "success", data: [payload] }))
      }, 100);

    })

    counter++

    console.log(counter)

    return result
    //return JSON.stringify({ statusCode: "success", data: [] })
  })
}

main()
```
