### ISSUE TITLE
Receiving `NatsError: "tls" SERVER_OPT_NA`

### ISSUE THREAD

**Issue by moatorres** [nats-io/nats.js#539]
Hello,

I'm having a hard time securing connections between `nats` and its stream consumers on a local Kubernetes cluster. Somehow`/etc/nats-config/nats.conf` is being incorrectly rendered. I've been trying to find the source, but `nats-base-client` is somewhat cryptic to me. 

Particularly [`checkOptions`](https://github.com/nats-io/nats.deno/blob/12ac9a46e43cee932cc03acaf1931aad4593a961/nats-base-client/options.ts#L137), referenced [here](https://github.com/nats-io/nats.deno/blob/12ac9a46e43cee932cc03acaf1931aad4593a961/src/deno_transport.ts#L82). Not sure how/where `peekInfo` evaluates [`tls_required`](https://github.com/nats-io/nats.deno/blob/12ac9a46e43cee932cc03acaf1931aad4593a961/src/deno_transport.ts#L102).

```ts
const nats = await connect({
  servers: 'nats://nats.default.svc.cluster.local:4222',
  name: 'sandbox-api',
  tls: {
    ca: process.env.NATS_CA,
    key: process.env.NATS_KEY,
    cert: process.env.NATS_CERT,
  },
})
```

```js
[sandbox-api] NatsError: tls
[sandbox-api]     at checkOptions (/home/usr/app/node_modules/nats/nats-base-client/options.ts:138:11)
[sandbox-api]     at NodeTransport.<anonymous> (/home/usr/app/node_modules/nats/src/node_transport.ts:67:19)
[sandbox-api]     at Generator.next (<anonymous>)
[sandbox-api]     at fulfilled (/home/usr/app/node_modules/nats/lib/src/node_transport.js:5:58)
[sandbox-api]     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
[sandbox-api]   code: 'SERVER_OPT_NA',
[sandbox-api]   chainedError: undefined
[sandbox-api] }
```

```yaml
image: nats:alpine
pullPolicy: IfNotPresent
natsbox.enabled: false
cluster.enabled: false
tls.secret.name: nats-client-tls
tls.allowNonTLS: true
tls.ca: 'ca.crt'
tls.cert: 'tls.crt'
tls.key: 'tls.key'
reloader.enabled: false
exporter.enabled: false
jetstream.enabled: true
```

`ConfigMap` rendered:

```yaml
apiVersion: v1
data:
  nats.conf: |
    # NATS Clients Port
    port: 4222

    # PID file shared with configuration reloader.
    pid_file: "/var/run/nats/nats.pid"

    ###############
    #             #
    # Monitoring  #
    #             #
    ###############
    http: 8222
    server_name:$POD_NAME
    lame_duck_grace_period: 10s
    lame_duck_duration: 30s
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: nats
    meta.helm.sh/release-namespace: default
  creationTimestamp: '2022-12-15T17:25:25Z'
  labels:
    app.kubernetes.io/instance: nats
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.9.9-alpine
    helm.sh/chart: nats-0.19.3
  name: nats-config
  namespace: default
  resourceVersion: '92935'
  uid: b38d685d-6cd4-4188-9946-afd588963b33
```

What am I missing?

**Comment by moatorres** [comment]
Closing this issue as I've managed to deploy and secure client comms. Turns out that the issue was actually the structure of the `values.yaml`. Helm silently "failed" to point syntax errors from my side. Once I've got that sorted, everything went well! Happy new year!
