### ISSUE TITLE
One stream, one consumer, one pullSubscription, filtered consumer not unique on workqueue stream (error 10100)

### ISSUE THREAD

**Issue by whalderman** [nats-io/nats.js#566]
I'm new to NATS and have spent the last two days trying to figure out what's wrong with my code.

Repro: https://github.com/whalderman/nats-debug

```
/home/bcj115/code/nats-debug/node_modules/nats/lib/nats-base-client/jsutil.js:203
            return new error_1.NatsError(description, `${code}`);
                   ^

NatsError: filtered consumer not unique on workqueue stream
    at checkJsErrorCode (/home/bcj115/code/nats-debug/node_modules/nats/lib/nats-base-client/jsutil.js:203:20)
    at ConsumerAPIImpl.parseJsResponse (/home/bcj115/code/nats-debug/node_modules/nats/lib/nats-base-client/jsbaseclient_api.js:89:55)
    at ConsumerAPIImpl.<anonymous> (/home/bcj115/code/nats-debug/node_modules/nats/lib/nats-base-client/jsbaseclient_api.js:71:25)
    at Generator.next (<anonymous>)
    at fulfilled (/home/bcj115/code/nats-debug/node_modules/nats/lib/nats-base-client/jsbaseclient_api.js:19:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: '400',
  chainedError: undefined,
  api_error: {
    code: 400,
    err_code: 10100,
    description: 'filtered consumer not unique on workqueue stream'
  }
}
```

I only have one consumer, yet it's not unique...
Is the error message accurately describing the problem?

It's also possible my understanding is still lacking.

**Comment by aricart** [comment]
Can you actually list the consumers - use `nats consumer report streamName`
For a workqueue, the consumers must not overlap subjects. If the consumer already exists and for some reason you changed your filter (the first argument on the subscribe) - it could be trying to create a new consumer which doesn't match the existing one.

I would suggest in your options passed to subscribe, you use the `bind` option - to insure that it simply just attaches.

**Comment by aricart** [comment]
OK - the issue is that your consumer is not named, so eventhough you created it is not a durable, so there will be an attempt to create a second consumer when you try to subscribe. Since you are doing a pull consumer and I think from another discussion in slack you were trying to horizontally scale, you should create a durable, and then simply bind. I will update your example and send you a PR.

**Comment by aricart** [comment]
I fixed your example

https://github.com/whalderman/nats-debug/issues/1

**Comment by whalderman** [comment]
@aricart -- thanks for the help!
> there will be an attempt to create a second consumer when you try to subscribe
I was not aware of this, thanks for the info!

**Comment by whalderman** [comment]
Wait... I was aware of that, which is why I passed the consumer info to the pull subscribe.

> you should create a durable, and then simply bind

I tried this previously as well, with no luck -- something is still off with my understanding.  
Can `JetStreamPullSubscription`s not be consumed with an async iterator?

**Comment by aricart** [comment]
Sure it can!

**Comment by whalderman** [comment]
Ahhhh, okay, thank you for that reference, I finally figured out my misunderstanding.

I had thought the pull subscription would be more automatic -- I didn't realize I still needed to call `.pull()` after the iterator was set.

Thanks @aricart!
