### ISSUE TITLE
Setting headers only to true results in error

### ISSUE THREAD

**Issue by dermasmid** [nats-io/nats.js#634]
### Observed behavior

if the consumer `headers_only` is set to true, consuming will fail with the following error

```
err: NatsError: Bad JSON
      at NatsError.errorForCode (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/node_modules/nats/lib/nats-base-client/core.js:143:16)
      at Object.decode (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/node_modules/nats/lib/nats-base-client/codec.js:62:40)
      at MsgImpl.json (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/node_modules/nats/lib/nats-base-client/msg.js:87:48)
      at JsMsgImpl.json (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/node_modules/nats/lib/jetstream/jsmsg.js:191:25)
      at Array.<anonymous> (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/module/sources/natsSource.js:82:39)
      at execute (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/module/transforms/transform.js:121:55)
      at /Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/module/transforms/transform.js:121:77
      at /Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/module/transforms/transform.js:80:34
      at AsyncLocalStorage.run (node:async_hooks:346:14)
      at Array.<anonymous> (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/module/transforms/transform.js:49:50) {
    code: 'BAD_JSON',
    chainedError: SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at Object.decode (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/node_modules/nats/lib/nats-base-client/codec.js:59:29)
        at MsgImpl.json (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/node_modules/nats/lib/nats-base-client/msg.js:87:48)
        at JsMsgImpl.json (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/node_modules/nats/lib/jetstream/jsmsg.js:191:25)
        at Array.<anonymous> (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/module/sources/natsSource.js:82:39)
        at execute (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/module/transforms/transform.js:121:55)
        at /Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/module/transforms/transform.js:121:77
        at /Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/module/transforms/transform.js:80:34
        at AsyncLocalStorage.run (node:async_hooks:346:14)
        at Array.<anonymous> (/Users/cheskeltwersky/Documents/triplewhale/backend/packages/saber/module/transforms/transform.js:49:50)
```

### Expected behavior

headers_only should not try to parse the body as json

### Server and client version

nats: 2.10.17
client: 2.28.0

**Comment by aricart** [comment]
The Javascript client doesn't initiate any JSON parsing on user data... Can
you verify your handler isn't calling decode on a codec or json() on your
transforms.

**Comment by dermasmid** [comment]
i was calling msg.json() which was calling the failure, i think it would be nice if the client would not fail, but for now im adding a check in the user code

**Comment by aricart** [comment]
msg.json() asumes you know what you are parsing...
